apiVersion: apps/v1                 # Version de la API (puede cambiar entre versiones de k8s)
kind: StatefulSet                   # TIPO: 
metadata:                           # Metadatos del Deployment
  name: sts-mysql
  labels:
    app: sts-mysql                 # este label existe a nivel de deployment
spec:                              # Spec del DEPLOYMENT
  serviceName: svc-headless-mysql
  selector:
    matchLabels:
      app: mysql
  replicas: 1                      # indica al controlador que ejecute 2 pods
  template:                        # Aquí comienza el bloque del POD
    metadata:                      # Metadatos del POD
      labels:                      # Labels del POD (distintos a los del deployment!)
        app: mysql
    spec:                          # Especificación del POD
      containers:                  # Declaración de los contenedores del POD
      - name: mysql
        image: mysql
        ports:
        - containerPort: 3306