apiVersion: v1
kind: Pod
metadata:
  labels:
  name: pod-busybox-conlog
spec:
  containers:
  - image: busybox
    name: pod-busybox-conlog
    command:
      - "sh"
      - "-c"
    args:
      - |
        while true; do
          echo "Hello kubernates"
          sleep 1
        done   
