apiVersion: v1
kind: Pod
metadata:
  name: pod-busybox-command-args
spec:
  containers:
  - name: con-busybox
    image: busybox
    command: ['sh', '-c'] 
    args:
    - |
      echo Hello Kubernetes! 
      sleep 30    
